[Desktop Entry]
Name=Yaru-cinnamon
Type=X-GNOME-Metatheme
Comment=Ubuntu Yaru-cinnamon theme
Encoding=UTF-8

[X-GNOME-Metatheme]
GtkTheme=Yaru-cinnamon
MetacityTheme=Yaru
IconTheme=Yaru-cinnamon
CursorTheme=Yaru
CursorSize=24
X-Yaru-Dark=false
X-Yaru-Accent-Name=cinnamon
X-Yaru-Accent-Color=#dd682a
/home/initu/Downloads/yaru-master/build/gtk/src/Yaru-cinnamon-cinnamon-accent-color-info.scss:50 DEBUG: Contrast optimized accent is #e27d48
