#!/bin/sh

# Start: set -e to abort script on error
set -e

# Basically remove all the Debian Junk and fix Cinnamon-Layout icon.
#
# When meta installs the cinnamon packages and everything-the debian
# wallpapers from when packaged gets bundled up in them. For the Ubuntu
# Cinnamon Environment, this is not needed and therefore should be
# removed.
#
# As for the Cinnamon DE is built on GNOME, we keep the GNOME
# wallpapers as they fit with the default themes such as Adwaita, and
# therefore has a right to stay.
#
# For Layout icon-Wasta-Linux makes it and their icon doesn't fit with
# our icon theme-so we replace it.

# Remove the physical actual wallpapers-the directory is only used by
# the debian wallpapers instead of in usr/share/backgrounds
rmDirs=("/usr/share/wallpapers" "/usr/share/gnome-background-properties/debian-*" "/usr/share/plymouth/themes/futureprototype" "/usr/share/plymouth/themes/joy" "/usr/share/plymouth/themes/lines" "/usr/share/plymouth/themes/moonlight" "/usr/share/plymouth/themes/softwaves" "/usr/share/plymouth/themes/spacefun")

for d in ${rmDirs[@]}; do
  if [[ -f d]] then
    rm -r d
  fi
fi

if [[ -f /usr/share/icons/hicolor/scalable/apps/cinnamon-layout.svg]]
then
  rm /usr/share/icons/hicolor/scalable/apps/cinnamon-layout.svg
fi

cp /usr/share/icons/hicolor/scalable/categories/cs-panel.svg /usr/share/icons/hicolor/scalable/apps/cinnamon-layout.svg

# Debhelper: Add token
#DEBHELPER#
